version: 2
before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/soderluk/nirimgr/config.Version={{ .Tag }}
      - -X github.com/soderluk/nirimgr/config.CommitSHA={{ .ShortCommit }}
      - -X github.com/soderluk/nirimgr/config.BuildDate={{ .Date }}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
