builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
    main: ./
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -extldflags '-static'
      - -s -w
      - -X github.com/soderluk/nirimgr/config.Version={{.Version}}
      - -X github.com/soderluk/nirimgr/config.CommitSHA={{.FullCommit}}
      - -X github.com/soderluk/nirimgr/config.BuildDate={{.Date}}
