builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
    main: ./
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -extldflags '-static'
      - -s -w
      - -X config.Version={{.Version}}
      - -X config.CommitSHA={{.FullCommit}}
      - -X config.Date={{.Date}}
