name: "Run tests"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  lint:
    uses: soderluk/.github/workflows/lint.yaml
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - run: go test -v ./...
